---
title: "CENSO_salud_edad"
output: html_document
---

## POBLACIÓN MIGRANTE
# Cargar librerías
```{r librerias, echo=TRUE, message=FALSE, warning=FALSE}
# Cargar librerías
library(tidyverse)  # Manipulación y visualización de datos
library(readxl)     # Lectura de archivos Excel
library(janitor)    # Limpieza y estandarización de nombres de variables
library(knitr)      # Generación de tablas en documentos dinámicos
library(kableExtra) # Mejora en la presentación de tablas
```

# Cargar la base de datos de salud de CENSO 2023
```{r carga, echo=TRUE, message=FALSE, warning=FALSE}
# Carga del archivo xlsX con la base de datos de CENSO 2023
censo_salud <- read_excel("data/CENSO_salud_edades.xlsx", sheet = "Migrante")
# Verificar los nombres de las variables
names(censo_salud)
censo_salud
```
# Limpiar variable
```{r limpiar_variable, echo=TRUE}
# Limpiar la variable de salud
censo_salud[censo_salud== "-"] <- "0" #Reemplazar guiones por cero como caracter
censo_salud <- censo_salud %>%
  rename (Salud = ...1) %>%
  mutate(across(`105 Y MÁS`, ~as.numeric(.))) # Convertir última columna a numérico

# Verificar la limpieza
censo_salud

```

# Unir columnas por grupos de edad
```{r unir_columnas, echo=TRUE}
# Unir columnas por grupos de edad
censo_salud <- censo_salud %>%
  mutate(`20 A 34` = `20 A 24` + `25 A 29` + `30 A 34`,
         `35 A 54` = `35 A 39` + `40 A 44` + `45 A 49`+`50 A 54`,
         `+55` = `55 A 59` + `60 A 64` + `65 A 69` + `70 A 74` + `75 A 79` + `80 A 84` + `85 A 89` + `90 A 94` + `95 A 99` + `100 A 104` + `105 Y MÁS`) %>%
  select(Salud, `20 A 34`, `35 A 54`, `+55`)
# Verificar la unión de columnas
censo_salud
```
# Tabla de frecuencias
```{r tabla_frecuencias, echo=TRUE}
censo_salud_frecuencias <- censo_salud %>%
  mutate(Porcentaje_20a34= `20 A 34` / sum(`20 A 34`, na.rm = TRUE) * 100,
         Porcentaje_35a54 = `35 A 54` / sum(`35 A 54`, na.rm = TRUE) * 100,
         Porcentaje_mayores55 = `+55` / sum(`+55`, na.rm = TRUE) * 100) %>%
  select(Salud, Porcentaje_20a34, Porcentaje_35a54, Porcentaje_mayores55)
censo_salud_frecuencias
```
