---
title: "CENSO_salud"
output: html_document
---
## POBLACIÓN MIGRANTE
# Cargar librerías
```{r librerias, echo=TRUE, message=FALSE, warning=FALSE}
# Cargar librerías
library(tidyverse)  # Manipulación y visualización de datos
library(readxl)     # Lectura de archivos Excel
library(janitor)    # Limpieza y estandarización de nombres de variables
library(knitr)      # Generación de tablas en documentos dinámicos
library(kableExtra) # Mejora en la presentación de tablas
```

# Cargar la base de datos de salud de CENSO 2023
```{r carga, echo=TRUE, message=FALSE, warning=FALSE}
# Carga del archivo xlsX con la base de datos de CENSO 2023
censo_salud <- read_excel("../data/CENSO_salud.xlsx", sheet = "Migrante")
# Verificar los nombres de las variables
names(censo_salud)
censo_salud
```
# Tabla de frecuencias

```{r tabla_frecuencias, echo=TRUE}
censo_salud_frecuencias <- censo_salud %>%
  rename(Salud = "...1", Mujer = `Mujer / Femenino`, Hombre = `Varón / Masculino`) %>%
  select(Salud, Mujer, Hombre) %>%
  mutate(Mujer = as.numeric(gsub("\\s+","",Mujer)),  # Eliminar espacios y convertir a numérico
         Hombre = as.numeric(gsub("\\s+","",Hombre))) %>%
  mutate(Porcentaje_Mujer = Mujer / sum(Mujer) * 100,
         Porcentaje_Hombre = Hombre / sum(Hombre) * 100) %>%
  select(Salud, Porcentaje_Mujer, Porcentaje_Hombre)

censo_salud_frecuencias

  
```
